# Generated by Django 5.1 on 2024-08-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_email_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
